#!/bin/sh
#
# Only runs if there is no custom postswitch script

contains() {
  echo "${1}" | grep --fixed-strings --line-regexp "${2}" > /dev/null
  return $?
}

bspc_dual_monitor_setup() {
    bspc monitor "${1}" --reset-desktops D7
    bspc monitor eDP-1 --reset-desktops D1 D2 D3 D4 D5 D6
    bspc wm --reorder-monitors eDP-1 "${1}"
    bspc desktop --focus D1
}

bspc_dual_monitor_switch() {
  bspc desktop D1 --to-monitor eDP-1
  bspc desktop D2 --to-monitor eDP-1
  bspc desktop D3 --to-monitor eDP-1
  bspc desktop D4 --to-monitor eDP-1
  bspc desktop D5 --to-monitor eDP-1
  bspc desktop D6 --to-monitor eDP-1
  bspc desktop D7 --to-monitor "${1}"
  bspc desktop Desktop --remove
  if [ "${1}" = 'eDP-1' ]; then
    bspc monitor eDP-1 --reorder-desktops D1 D2 D3 D4 D5 D6 D7
  else
    bspc monitor eDP-1 --reorder-desktops D1 D2 D3 D4 D5 D6
    bspc wm --reorder-monitors eDP-1 "${1}"
    bspc desktop --focus D1
  fi
}

monitors=$(bspc query --monitors --names)
if contains "$monitors" 'HDMI-2'; then
  bspc_dual_monitor_switch 'HDMI-2'
elif contains "$monitors" 'DP-1'; then
  bspc_dual_monitor_switch 'DP-1'
else
  bspc_dual_monitor_switch 'eDP-1'
  # bspc monitor eDP-1 --reset-desktops D1 D2 D3 D4 D5 D6 D7
fi

sleep 0.5
"$HOME/.config/polybar/polybar"
sleep 0.5

for node in $(bspc query --nodes)
do
  echo "Changed $node"
  bspc node "$node" -t ~floating
  bspc node "$node" -t ~floating
done
