#! /bin/sh

/usr/lib/cinnamon-settings-daemon/csd-background &
nemo --no-default-window --no-desktop &
picom --daemon

sxhkd & #-f 50 &

if [ "$(bspc query -M | wc -l)" -eq "2" ]; then
  bspc wm --reorder-monitors HDMI-2 eDP-1
  bspc monitor HDMI-2 --reset-desktops D1 D2 D3
  bspc monitor eDP-1 --reset-desktops D4
else
  bspc monitor eDP-1 --reset-desktops D1 D2 D3 D4
fi

$HOME/.config/polybar/polybar
$HOME/.config/bspwm/monitors &

# --- Aesthetics {{{

bspc config -m primary bottom_padding 48

bspc config border_width  0
bspc config window_gap    16

bspc config split_ratio   0.50

# ---}}}

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config focus_follows_pointer   true
bspc config pointer_follows_monitor true

bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true

bspc rule --add Zathura state=tiled
bspc rule --add Soffice state=tiled # Workaround for issue #655

#bspc rule -a Gimp desktop=^8 state=floating follow=on
#bspc rule -a Chromium desktop=^2
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
