#! /bin/sh

sxhkd & #-f 50 &

picom --daemon
xsetroot -cursor_name left_ptr

/usr/lib/cinnamon-settings-daemon/csd-background &
nemo --no-default-window --no-desktop &

$HOME/.config/polybar/polybar &

# --- Aesthetics {{{

#bspc config -m primary bottom_padding 48
bspc config -m primary bottom_padding 32

bspc config border_width  0
#bspc config window_gap    16
bspc config window_gap    8

bspc config split_ratio   0.50

# ---}}}

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config focus_follows_pointer   true
bspc config pointer_follows_monitor true

bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true

if [ "$(bspc query -M | wc -l)" -eq "2" ]; then
  bspc monitor HDMI-2 --reset-desktops D1 D2 D3 D4 D5 D6
  bspc monitor eDP-1 --reset-desktops D7
  bspc wm --reorder-monitors HDMI-2 eDP-1
  bspc desktop --focus D1
else
  bspc monitor eDP-1 --reset-desktops D1 D2 D3 D4 D5 D6 D7
fi

bspc rule --add Zathura state=tiled
bspc rule --add Soffice state=tiled # Workaround for issue #655

bspc rule --add 'Gscreenshot' state=floating

#bspc rule --add zoom state=floating center=true rectangle=2560x1440+0+0
bspc rule --add *:*:'Zoom Meeting' desktop=D7 state=floating center=on \
  rectangle=1728x824+0+0
  #rectangle=1280x720+0+0

bspc rule --add 'zoom' desktop=D7 state=floating center=on \
  rectangle=1728x824+0+0
  #rectangle=1280x720+0+0

# Make Firefox pop-out video float in bottom right corner.
bspc rule --add firefox:Toolkit state=floating sticky=on \
  rectangle=320x180+1584+852

# Float Zotero selector bar.
bspc rule --add Zotero:*:'Quick Format Citation' state=floating center=on \
  follow=on
