#! /bin/sh

lemonbuddy_terminate noconfirm
compton -b

sxhkd -f 50 &
lemonbuddy_wrapper master &
nemo --no-default-window --no-desktop &

# --- Aesthetics {{{

bspc config -m primary bottom_padding 48

bspc config border_width  0
bspc config window_gap    16

bspc config split_ratio   0.50

# ---}}}

bspc config focus_follows_pointer   true
bspc config pointer_follows_monitor true

bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc monitor primary --reset-desktops 1 2 3 4
bspc monitor ^2 --reset-desktops 5 6 7 8

#bspc rule -a Gimp desktop=^8 state=floating follow=on
#bspc rule -a Chromium desktop=^2
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
