#! /bin/sh

bspc subscribe monitor | while read -r line; do
  case $line in
    monitor_add*|monitor_geometry*)
      if [ "$(bspc query -M | wc -l)" -eq "2" ]; then
        bspc wm --reorder-monitors HDMI-2 eDP-1
        bspc desktop D1 --to-monitor HDMI-2
        bspc desktop D2 --to-monitor HDMI-2
        bspc desktop D3 --to-monitor HDMI-2
        bspc desktop Desktop --remove
      else
        bspc desktop D1 --to-monitor eDP-1
        bspc desktop D2 --to-monitor eDP-1
        bspc desktop D3 --to-monitor eDP-1
        bspc monitor eDP-1 --reorder-desktops D1 D2 D3 D4
      fi
      #$HOME/.config/polybar/launch.sh
      ;;
    *)
    ;;
  esac
done &

