#!/bin/sh

~/.config/polybar/polybar &

if bspc query --monitors; then
  bspc desktop D1 --to-monitor eDP-1
  bspc desktop D2 --to-monitor eDP-1
  bspc desktop D3 --to-monitor eDP-1
  bspc desktop D4 --to-monitor eDP-1
  bspc desktop D5 --to-monitor eDP-1
  bspc monitor eDP-1 --reorder-desktops D1 D2 D3 D4 D5
fi
